<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>$schema</key>
	<string>https://raw.githubusercontent.com/martinring/tmlanguage/master/tmlanguage.json</string>
	<key>$version</key>
	<string>v0.0.3</string>
	<key>name</key>
	<string>RAScript</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#statements</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>statements</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#controls</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#booleans</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#strings</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#numbers</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#class-definitions</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#function-definitions</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#function-names</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#header</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#comments</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#variable-language-this</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#variable-assignment</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#variable-other</string>
				</dict>
			</array>
		</dict>
		<key>controls</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>keyword.control.rascript</string>
					<key>match</key>
					<string>\b(if|else|for|in|return)\b</string>
				</dict>
			</array>
		</dict>
		<key>booleans</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>constant.language.boolean.rascript</string>
					<key>match</key>
					<string>\b(true|false)\b</string>
				</dict>
			</array>
		</dict>
		<key>strings</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>string.quoted.double.rascript</string>
					<key>match</key>
					<string>(?:".*?")</string>
				</dict>
			</array>
		</dict>
		<key>numbers</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>constant.numeric.decimal.rascript</string>
					<key>match</key>
					<string>\b[0-9]+\b</string>
				</dict>
				<dict>
					<key>name</key>
					<string>constant.numeric.hexadecimal.rascript</string>
					<key>match</key>
					<string>(?i)\$\b\h+\b|\b0x\h+\b</string>
				</dict>
			</array>
		</dict>
		<key>class-definitions</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>(\bclass\b)[\t ]*(([a-zA-Z_][\w]*)|(.+))</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.class.rascript</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>entity.name.class.rascript</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>invalid.illegal.identifier.rascript</string>
						</dict>
					</dict>
				</dict>
			</array>
		</dict>
		<key>function-definitions</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>(\bfunction\b)[\t ]*(([a-zA-Z_][\w]*)|(.+))\(</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.function.rascript</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>entity.name.function.rascript</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>invalid.illegal.identifier.rascript</string>
						</dict>
					</dict>
					<key>end</key>
					<string>\)</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>match</key>
							<string>(?:[\w]+\s+[\w]+)</string>
							<key>name</key>
							<string>invalid.illegal.identifier.rascript</string>
						</dict>
						<dict>
							<key>match</key>
							<string>(?:[^\s\,!]*[\%\!\@\#\$\%\^\&amp;\*\-\=\+\[\]\{\}\;\:\'"\.\&lt;\&gt;\/\?]+[^\s\,]*)</string>
							<key>name</key>
							<string>invalid.illegal.identifier.rascript</string>
						</dict>
						<dict>
							<key>match</key>
							<string>(?:[a-zA-Z_][\w]*)</string>
							<key>name</key>
							<string>variable.parameter.rascript</string>
						</dict>
						<dict>
							<key>match</key>
							<string>(?:\w+)</string>
							<key>name</key>
							<string>invalid.illegal.identifier.rascript</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>function-names</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>(([0-9][\w+]*)|(\w+))\(</string>
					<key>captures</key>
					<dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>invalid.illegal.identifier.rascript</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>entity.name.function.rascript</string>
						</dict>
					</dict>
				</dict>
			</array>
		</dict>
		<key>header</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>comment.line.double-slash.rascript</string>
					<key>match</key>
					<string>^//\s*(#ID)\s*=\s*(\d+)$</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.other.id.rascript</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>constant.numeric.id.rascript</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>name</key>
					<string>comment.line.double-slash.rascript</string>
					<key>match</key>
					<string>^//\s*(#MinimumVersion)\s*=\s*(\d+(\.\d)?)$</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.other.version.rascript</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>constant.numeric.version.rascript</string>
						</dict>
					</dict>
				</dict>
			</array>
		</dict>
		<key>comments</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>/\*</string>
					<key>captures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.comment.block.rascript</string>
						</dict>
					</dict>
					<key>end</key>
					<string>\*/</string>
					<key>name</key>
					<string>comment.block.rascript</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>//</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.comment.single.rascript</string>
						</dict>
					</dict>
					<key>end</key>
					<string>$</string>
					<key>name</key>
					<string>comment.line.double-slash.rascript</string>
				</dict>
			</array>
		</dict>
		<key>variable-language-this</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>variable.language.this.rascript</string>
					<key>match</key>
					<string>\b(this)\b</string>
				</dict>
			</array>
		</dict>
		<key>variable-assignment</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>comment</key>
					<string>left hand side of variable assignment</string>
					<key>match</key>
					<string>([a-zA-Z_][\w]*)[\t ]*=</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>variable.other.assignment.rascript</string>
						</dict>
					</dict>
				</dict>
			</array>
		</dict>
		<key>variable-other</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>comment</key>
					<string>different variables around the file being used, not assignment</string>
					<key>match</key>
					<string>([a-zA-Z_][\w]*)</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>variable.other.rascript</string>
						</dict>
					</dict>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.rascript</string>
</dict>
</plist>
