on:
  push:
    tags:
      - "v*.*.*"

permissions:
  contents: write

name: Release Files
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: make package
      - run: mv RAScript.sublime-package RAScript-${{ github.ref_name }}.sublime-package
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          body: Release tag ${{ github.ref_name }}
          files: |
            RAScript.sublime-package