on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"

permissions:
  contents: write

name: Release Files
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: make package
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          body: Release tag ${{ github.ref_name }}
          files: |
            RAScript.sublime-package